In [16]:
import numpy as np;

a=np.arange(30).reshape(2,3,5)
a.sum((0)),a.sum((1)),a


(array([[15, 17, 19, 21, 23],
        [25, 27, 29, 31, 33],
        [35, 37, 39, 41, 43]]),
 array([[15, 18, 21, 24, 27],
        [60, 63, 66, 69, 72]]),
 array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],
 
        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]]))

通过np的函数实现对矩阵的操作
按照参数传入的类型，可以将函数分为3类：
部分函数无需参数
```
a.shape
a.size
```
部分函数参数为矩阵如
```
np.arange()
np.array()
```
对于最后一种函数的输入，因为不能在设计函数时就确定输入值的个数，因此一般用括号将同种的变量括起来
```
np.ones((2,5))
np.zeros((3,4))
np.reshape((2,6))
np.concat((a,b),0)
```
而一般的基础运算比如+-等等，均默认改为对元素的操作
而若操作符两边的张量形状不同，则python会有广播机制：
从最右侧的维度开始，逐维比较两个数组的形状。
    如果两个维度相等或其中一个为1，则兼容。
    如果其中一个数组的维度缺失（即长度不足），则在该维度上虚拟扩展为1。
会将1维度进行复制以匹配高维

元素的存取
单个元素
```
a[1,2]
```
范围存取
```
a[-1,:]=>a的最后1行，所有列
a[3:7:2,2:9:3]=>a的3到6行，隔2行取一次，2到9列，隔3列取一次
```